import { Badge } from "@/components/ui/badge"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"

type EndpointDoc = {
  id: string
  title: string
  method: "GET" | "POST"
  path: string
  description: string
  requestNotes: string[]
  responseNotes: string[]
  curl: string
  responseExample: string
}

const apiBaseUrl = "http://127.0.0.1:8001/api"
const seededUserId = "52db9059-b2d7-4ce9-88f0-f2c26ce1b4f6"

const endpointDocs: EndpointDoc[] = [
  {
    id: "search-users",
    title: "Search Users",
    method: "GET",
    path: "/users",
    description:
      "Returns directory entries from the dedicated activity user directory. Search matches both user name and UUID.",
    requestNotes: [
      "Optional query params: search, limit",
      "limit defaults server-side and remains bounded",
      "Used by the UI user picker and empty states",
    ],
    responseNotes: [
      "Returns user summary objects, not raw UUID strings",
      "Response includes meta.search, meta.limit, and meta.count",
    ],
    curl: `curl "${apiBaseUrl}/users?search=seed&limit=10"`,
    responseExample: `{
  "data": [
    {
      "id": "${seededUserId}",
      "name": "Seeded Demo User"
    }
  ],
  "meta": {
    "search": "seed",
    "limit": 10,
    "count": 1
  }
}`,
  },
  {
    id: "create-user",
    title: "Create User",
    method: "POST",
    path: "/users",
    description:
      "Creates a directory user with a server-generated UUID. This is the authoritative source for selectable users in the UI.",
    requestNotes: [
      "Body requires name only",
      "UUID is generated by the API",
      "Names are not required to be unique",
    ],
    responseNotes: [
      "Returns the created user summary in data",
      "Status code is 201 Created",
    ],
    curl: `curl -X POST "${apiBaseUrl}/users" \\
  -H "Content-Type: application/json" \\
  -d '{
    "name": "Planning Demo User"
  }'`,
    responseExample: `{
  "data": {
    "id": "b61e427d-ecf8-43c1-a4ba-381d6acee1d3",
    "name": "Planning Demo User"
  }
}`,
  },
  {
    id: "ingest-event",
    title: "Ingest Event",
    method: "POST",
    path: "/events",
    description:
      "Persists a single activity event. This is the write path that feeds the dashboard metrics and recent activity timeline.",
    requestNotes: [
      "Required fields: user_id, event_type, occurred_at, payload",
      "event_type must be one of training_started, progress_made, points_scored, training_completed",
      "points_scored requires payload.points >= 1",
      "user_id must exist in activity_users",
    ],
    responseNotes: [
      "Returns the persisted event payload in data",
      "Validation failures return 422 with field-level errors",
    ],
    curl: `curl -X POST "${apiBaseUrl}/events" \\
  -H "Content-Type: application/json" \\
  -d '{
    "user_id": "${seededUserId}",
    "event_type": "points_scored",
    "occurred_at": "2026-03-06T10:15:00Z",
    "payload": {
      "points": 25,
      "reason": "quiz_bonus"
    }
  }'`,
    responseExample: `{
  "data": {
    "id": "8cf435f8-4e73-4303-a3f7-a28137cc4b2d",
    "user_id": "${seededUserId}",
    "event_type": "points_scored",
    "occurred_at": "2026-03-06T10:15:00+00:00",
    "payload": {
      "points": 25,
      "reason": "quiz_bonus"
    },
    "ingested_at": "2026-03-06T10:15:03+00:00"
  }
}`,
  },
  {
    id: "recent-activities",
    title: "Get Recent Activities",
    method: "GET",
    path: "/users/{user_id}/activities",
    description:
      "Returns recent events for a user ordered by occurred_at descending. This powers the activity table and timeline chart.",
    requestNotes: [
      "Path param: user_id",
      "Optional query params: limit, from, to",
      "limit defaults to 20 and is capped server-side",
    ],
    responseNotes: [
      "Response includes items in data and request metadata in meta",
      "Events are scoped to the selected user only",
    ],
    curl: `curl "${apiBaseUrl}/users/${seededUserId}/activities?limit=20"`,
    responseExample: `{
  "data": [
    {
      "id": "b2b96d7f-c5fd-49c4-a343-89ed7c15f4b8",
      "user_id": "${seededUserId}",
      "event_type": "training_started",
      "occurred_at": "2026-03-05T11:12:13+00:00",
      "payload": {
        "training_id": "seed-training-101"
      },
      "ingested_at": "2026-03-06T11:12:13+00:00"
    }
  ],
  "meta": {
    "user_id": "${seededUserId}",
    "limit": 20,
    "from": null,
    "to": null,
    "count": 1
  }
}`,
  },
  {
    id: "engagement-metrics",
    title: "Get Engagement Metrics",
    method: "GET",
    path: "/users/{user_id}/metrics",
    description:
      "Returns the aggregate metrics model used by the dashboard summary cards. Metrics are computed server-side for a stable UI contract.",
    requestNotes: [
      "Path param: user_id",
      "Optional query params: from, to",
      "When omitted, the API defaults to the last 30 days",
    ],
    responseNotes: [
      "Includes event_counts plus derived totals such as active_days and latest_activity",
      "Validation rejects an invalid date range with 422",
    ],
    curl: `curl "${apiBaseUrl}/users/${seededUserId}/metrics"`,
    responseExample: `{
  "data": {
    "user_id": "${seededUserId}",
    "from": "2026-02-05T11:12:13+00:00",
    "to": "2026-03-06T11:12:13+00:00",
    "total_events": 4,
    "event_counts": {
      "training_started": 1,
      "progress_made": 1,
      "points_scored": 1,
      "training_completed": 1
    },
    "total_points": 25,
    "completed_trainings": 1,
    "started_trainings": 1,
    "progress_events": 1,
    "active_days": 4,
    "latest_activity": "2026-03-06T12:00:00+00:00"
  }
}`,
  },
]

export function ApiDocumentationPage() {
  return (
    <div className="space-y-5">
      <Card className="overflow-hidden bg-card">
        <CardHeader className="gap-4">
          <div className="space-y-4">
            <div className="space-y-1">
              <h1 className="text-3xl font-semibold tracking-tight">API Documentation</h1>
              <CardDescription className="max-w-3xl text-sm text-muted-foreground">
                This page documents the current Laravel API contract the UI uses:
                user directory search and creation, event ingestion, recent
                activities, and engagement metrics.
              </CardDescription>
            </div>
          </div>
        </CardHeader>
      </Card>

      <Card className="bg-card">
        <CardHeader className="gap-1">
          <CardTitle className="text-base">Event Type Contract</CardTitle>
          <CardDescription>
            The ingestion endpoint accepts a fixed event enum in this MVP.
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-wrap gap-2">
          <Badge variant="secondary">training_started</Badge>
          <Badge variant="secondary">progress_made</Badge>
          <Badge variant="secondary">points_scored</Badge>
          <Badge variant="secondary">training_completed</Badge>
        </CardContent>
      </Card>

      <Card className="bg-card">
        <CardHeader className="gap-1">
          <CardTitle className="text-base">Endpoints</CardTitle>
          <CardDescription>
            Request examples are curl-based. Response samples are representative
            of the current API shape.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Accordion type="single" collapsible className="w-full">
            {endpointDocs.map((endpoint) => (
              <AccordionItem key={endpoint.id} value={endpoint.id}>
                <AccordionTrigger className="gap-4">
                  <div className="flex min-w-0 flex-col gap-2 text-left md:flex-row md:items-center">
                    <div className="flex items-center gap-2">
                      <MethodBadge method={endpoint.method} />
                      <span className="font-semibold text-foreground">{endpoint.title}</span>
                    </div>
                    <code className="text-xs text-muted-foreground md:text-sm">
                      {endpoint.path}
                    </code>
                  </div>
                </AccordionTrigger>
                <AccordionContent className="space-y-5">
                  <p className="max-w-3xl text-sm leading-6 text-muted-foreground">
                    {endpoint.description}
                  </p>

                  <div className="grid gap-5 lg:grid-cols-2">
                    <div className="space-y-2">
                      <h3 className="text-sm font-semibold">Request Notes</h3>
                      <ul className="space-y-2 text-sm text-muted-foreground">
                        {endpoint.requestNotes.map((note) => (
                          <li key={note}>{note}</li>
                        ))}
                      </ul>
                    </div>
                    <div className="space-y-2">
                      <h3 className="text-sm font-semibold">Response Notes</h3>
                      <ul className="space-y-2 text-sm text-muted-foreground">
                        {endpoint.responseNotes.map((note) => (
                          <li key={note}>{note}</li>
                        ))}
                      </ul>
                    </div>
                  </div>

                  <Tabs defaultValue="request" className="gap-4">
                    <TabsList className="bg-card">
                      <TabsTrigger value="request">Request Example</TabsTrigger>
                      <TabsTrigger value="response">Response Example</TabsTrigger>
                    </TabsList>
                    <TabsContent value="request">
                      <pre className="overflow-x-auto rounded-xl bg-muted p-4 text-xs leading-6 text-foreground">
                        {endpoint.curl}
                      </pre>
                    </TabsContent>
                    <TabsContent value="response">
                      <pre className="overflow-x-auto rounded-xl bg-muted p-4 text-xs leading-6 text-foreground">
                        {endpoint.responseExample}
                      </pre>
                    </TabsContent>
                  </Tabs>
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </CardContent>
      </Card>
    </div>
  )
}

function MethodBadge({ method }: { method: EndpointDoc["method"] }) {
  const variant = method === "GET" ? "secondary" : "default"

  return <Badge variant={variant}>{method}</Badge>
}
